"""Typed contracts shared by orchestration nodes."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class Artifact:
    """A response artifact generated by a node."""

    kind: str
    path: Optional[str] = None
    url: Optional[str] = None
    title: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "kind": self.kind,
            "path": self.path,
            "url": self.url,
            "title": self.title,
            "metadata": self.metadata,
        }


@dataclass
class TraceStep:
    """Auditable execution step emitted by router and nodes."""

    stage: str
    label: str
    status: str = "done"
    agent: Optional[str] = None
    detail: str = ""
    duration_ms: Optional[float] = None
    artifact_count: Optional[int] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        item: Dict[str, Any] = {
            "stage": self.stage,
            "label": self.label,
            "status": self.status,
            "detail": self.detail,
        }
        if self.agent:
            item["agent"] = self.agent
        if self.duration_ms is not None:
            item["duration_ms"] = self.duration_ms
        if self.artifact_count is not None:
            item["artifact_count"] = self.artifact_count
        item.update(self.metadata)
        return item


@dataclass
class NodeContext:
    """Execution context passed to a node."""

    message: str
    conversation_id: Optional[str] = None
    run_id: Optional[str] = None
    orchestrator: Any = None
    domain_context: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class NodeResult:
    """Standard node result normalized before API serialization."""

    agent: str
    agent_name: str
    response: str
    agent_icon: str = ""
    chart_paths: List[str] = field(default_factory=list)
    artifacts: List[Artifact] = field(default_factory=list)
    sources: List[Dict[str, Any]] = field(default_factory=list)
    confidence: Optional[str] = None
    data_freshness: Dict[str, Any] = field(default_factory=dict)
    metric_context: Optional[str] = None
    period: Dict[str, Any] = field(default_factory=dict)
    data_scope_note: str = ""
    rerouted: bool = False
    trace: List[Dict[str, Any]] = field(default_factory=list)
    fallbacks: List[Dict[str, Any]] = field(default_factory=list)
    errors: List[Dict[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_legacy_dict(self) -> Dict[str, Any]:
        chart_path = self.chart_paths[0] if self.chart_paths else None
        return {
            "agent": self.agent,
            "agent_icon": self.agent_icon,
            "agent_name": self.agent_name,
            "response": self.response,
            "chart_path": chart_path,
            "chart_paths": self.chart_paths,
            "sources": self.sources,
            "confidence": self.confidence,
            "data_freshness": self.data_freshness,
            "metric_context": self.metric_context,
            "period": self.period,
            "data_scope_note": self.data_scope_note,
            "rerouted": self.rerouted,
            "trace": self.trace,
            "fallbacks": self.fallbacks,
            "errors": self.errors,
            **self.metadata,
        }

    @classmethod
    def from_legacy_dict(cls, payload: Dict[str, Any]) -> "NodeResult":
        chart_paths = list(payload.get("chart_paths") or [])
        chart_path = payload.get("chart_path")
        if chart_path and chart_path not in chart_paths:
            chart_paths.insert(0, chart_path)
        return cls(
            agent=payload.get("agent") or "normal",
            agent_icon=payload.get("agent_icon") or "",
            agent_name=payload.get("agent_name") or payload.get("agent") or "Agent",
            response=payload.get("response") or "",
            chart_paths=chart_paths,
            sources=payload.get("sources") or [],
            confidence=payload.get("confidence"),
            data_freshness=payload.get("data_freshness") or {},
            metric_context=payload.get("metric_context"),
            period=payload.get("period") or {},
            data_scope_note=payload.get("data_scope_note") or "",
            rerouted=bool(payload.get("rerouted", False)),
            trace=payload.get("trace") or [],
            fallbacks=payload.get("fallbacks") or [],
            errors=payload.get("errors") or [],
        )
